export const APP_ROUTES = {
  HOME: '(tabs)/index',
  ATTENDANCE: '/(tabs)/attendance',
  ATTENDANCE_HISTORY: '(tabs)/attendance/history',
  ATTENDANCE_DETAIL: '(tabs)/attendance/[id]',
  ACTIVITY: '(tabs)/activity',
  ENQUIRY: '(tabs)/enquiry',
  ENQUIRY_DETAIL: '(tabs)/enquiry/[id]',
  PROFILE: 'profile',
  LOGIN: 'login',
  FORGOT_PASSWORD: 'forgot-password',
  SIGN_UP: 'sign-up',
  SETTINGS: 'settings',
  NOTIFICATIONS: 'notifications',
  NOTIFICATIONS_SEND: 'notifications/send',
  NOTIFICATIONS_DETAIL: 'notifications/[id]',
  NOT_FOUND: '+not-found',
  ENQUIRY_ATTENDANCE_HISTORY: 'enquiry/attendance-history',
}